### ISSUE TITLE
Binary intent model publication in mleap format assumes a hotlead model

### ISSUE THREAD

**Issue by samikrc** [247-ai/FlashML#12]
Currently the mleap model publishing module expects a bunch of page level thresholds and mandatorily inserts a HotleadTransformer in the pipeline. This prevents us from publishing, say, an NL model in mleap format.

We get the following exception if those values are not present.
```
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'experiment.publish.thresholds'
        at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
        at com.typesafe.config.impl.SimpleConfig.getList(SimpleConfig.java:212)
        at com.typesafe.config.impl.SimpleConfig.getHomogeneousUnwrappedList(SimpleConfig.java:271)
        at com.typesafe.config.impl.SimpleConfig.getNumberList(SimpleConfig.java:294)
        at com.typesafe.config.impl.SimpleConfig.getDoubleList(SimpleConfig.java:320)
        at com.tfs.flashml.util.FlashMLConfig$.getDoubleArray(FlashMLConfig.scala:146)
        at com.tfs.flashml.publish.Publish$.generateMleap(Publish.scala:63)
        at com.tfs.flashml.core.PipelineSteps$.run(PipelineSteps.scala:289)
        at com.tfs.flashml.FlashML$.main(FlashML.scala:79)
        at com.tfs.flashml.FlashML.main(FlashML.scala)
```

**Comment by samikrc** [comment]
If required, we can introduce a config like "experiment.publish.isHotleadModel" expecting true/false, to insert the HotleadTransformer in the pipeline.

**Comment by samikrc** [comment]
Added config as proposed and fixed the issue. Merged with develop.
